### ISSUE TITLE
Bug in QuadContourGenerator::write_cache_quad?

### ISSUE THREAD

**Issue by mrexodia** [alandefreitas/matplotplusplus#14]
Today I was checking out the library and MSVC warns for https://github.com/alandefreitas/matplotplusplus/blob/359a775710e1b1fd5667281a0855806f149b7ab0/source/matplot/util/contourc.cpp#L1771

`BOUNDARY_S` returns a `bool` do the expression is `bool > 0`

**Comment by alandefreitas** [comment]
I'll have a look at it. This is a small adaptation on the algorithm matplotlib uses for generating contours [(link)](https://github.com/matplotlib/matplotlib/blob/master/src/_contour.h). Generating contours is more complicated than it seems at first so I needed this external help. Solving problems there is not as easy as solving problems in my own code, so this review might take a while.

**Comment by alandefreitas** [comment]
`BOUNDARY_S(quad)` does return a bool, so it doesn't really make sense to compare it with `BOUNDARY_S(quad) > 0`.
This is just a `std::cout` and the functions `write_cache` and `write_cache_quad` are not really being used anyway (it's just something that came with the original code) so that's not a problem. I could safely change `(BOUNDARY_S(quad) > 0)` for `BOUNDARY_S(quad)` but I'll try to understand the logic behind that to fix everything at once.

**Comment by alandefreitas** [comment]
#55

**Comment by mdumar91** [comment]
I would like to work on that , can you suggest me ways to get started?

**Comment by alandefreitas** [comment]
Hi @mdumar91! Thanks.

The contourc functions are based on the matplotlib contour generation algorithm, which is not as efficient or organized according to C++ common practices. 

- @lacc97 started a great PR https://github.com/alandefreitas/matplotplusplus/pull/55 to change that to an implementation based on Gnuplot's algorithm. 
- In the meanwhile, @leha-bot wrote an exceptional PR https://github.com/alandefreitas/matplotplusplus/pull/81 with a vector view that solved the main problem with the matplotlib adaptation for this matplotplusplus. This somewhat superseded https://github.com/alandefreitas/matplotplusplus/pull/55 because the matplotlib implementation was working fine after that.

A general problem is that lots source files give people lots of warnings on MSVC. Although we always work with pedantic warnings turned on https://github.com/alandefreitas/matplotplusplus/blob/4a679e2ec0e0a6287c8273679fbbebd6871527ae/CMakeLists.txt#L50, the library was originally written on GCC, and MSVC (correctly) gives lots of warnings about implicit casts. This is the only kind of warnings left on any platform. 

Solving this first problem is a matter of compiling the whole library with MSVC, let it warn you about these implicit casts, and put a static_cast where appropriate. Or simply remove unnecessary implicit casts and ugly patterns like `BOUNDARY_S(quad) > 0` for a boolean instead of just `BOUNDARY_S(quad)`. Ideally, we would test the examples with pedantic warnings too.

As for the problems with the matplotlib implementation in contourc.cpp only, besides these implicit casts, it's a matter of modernizing it a little bit. The original code is using a lot of C-style (or C with vectors) programming and it doesn't seem to be updated very often. The [algorithm itself](https://github.com/matplotlib/matplotlib/blob/master/src/_contour.cpp) seems to be pretty much ok after https://github.com/alandefreitas/matplotplusplus/pull/81 though. 

Off the top of my head, modernizing that would be things like:

- converting the ugly macros to constexpr functions or values, 
- fixing any weird patterns
- putting things in their proper scopes
- splitting classes into separate files
- rename anything that is not clear
- refactoring some names to snake_case

Let me know if you need any help to get started with any of these things. That is also on my to-do list, but I'm working hard on a better foundational backend for the library at the moment and this is taking a lot of time.

**Comment by nikkaramessinis** [comment]
Hi, 
Just sent you a pull request fixing on those warnings, changing enums to enum class and will do some further refactoring like the suggested contexpr changes if that's fine with you.
