### ISSUE TITLE
Mouse Scroll in 3D plots only alters the scale in the XY plane, not Z

### ISSUE THREAD

**Issue by StanJBrown** [alandefreitas/matplotplusplus#156]
**Feature category**
- [ ] *enhancement - build system*
- [ ] *enhancement - backends*
- [ ] *enhancement - build system*
- [x] *enhancement - documentation*
- [x] *enhancement - plot categories*

**The problem**
First of, awesome library, you have save me so much time with writing stuff to file, or protobuf files and combining zmq with matplot lib in python or unity. 

I have been using the 3D plotting a lot and noticed that when you scroll the mousewheel, only the XY plane is scaled. This causes the plot to get quite distorted in the Z planes. 

I have worked around this for now by just ensuring the plot limits are always the same in xyz, but I was wondering did I miss something in the docs or is this feature not yet implemented  or perhaps a limitation of GNU plot?

**The solution I'd like**
It would be nice to be scale all axes equally (xyz)

**Alternatives I've considered**

**Additional context**

**Comment by matthew-hennefarth** [comment]
I believe this is an ~~issue~~ *feature* with gnuplot in general since matplot++ doesn't change the interactivity with the gnuplot window. You might want to look at this [stack overflow](https://stackoverflow.com/questions/23345510/mouse-in-gnuplot-x11) discussion as it might point you in the right directions for finding your key bindings. I find that using a combination of shift-mouse wheel and shift-command-mouse wheel yields different changes to the view in a 3D gnuplot window.

Hope this helps!

**Comment by StanJBrown** [comment]
Thanks! For the tip. What a wonderful "feature" from gnuplot.
