### ISSUE TITLE
plot title shows "enhanced"

### ISSUE THREAD

**Issue by remz1337** [alandefreitas/matplotplusplus#162]
**Bug category**

- [ ] *bug - compilation error*
- [ ] *bug - compilation warning*
- [x] *bug - runtime error*
- [ ] *bug - runtime warning*
- [ ] *bug - logic error*

**Describe the bug**

The title of my plot show "enhanced" afterward
![image](https://user-images.githubusercontent.com/9980037/122423091-a9a3f400-cf5b-11eb-9f35-b849e88b2aac.png)

**Steps to Reproduce**

```
std::vector<double> x = randn(1000, 0, 1);
matplot::hist(x, 10);
matplot::title("test");
matplot::save("barchart.jpg");

```

**Platform**

- [ ] *cross-platform issue - linux*
- [x] *cross-platform issue - windows*
- [ ] *cross-platform issue - macos*

**Environment Details:**
 - OS: Windows
 - OS Version: 10 x64
 - Compiler: MSVC
 - Compiler version: 2019

**Comment by remz1337** [comment]
@alandefreitas just wondering if you might have any idea about this issue? I want to include these graphs in my research but it doesn't look very professional with the "enhanced" text appended to the title.

Thanks

**Comment by alandefreitas** [comment]
I don't really know what's causing this bug, but while this issue is not fixed, you can turn [this](https://github.com/alandefreitas/matplotplusplus/blob/95075dc7f960ed920160be510d64638c1260d429/source/matplot/backend/gnuplot.h#L76) on to see what gnuplot is generating and find why this "enhancement" is being included in the title. Another workaround, if you just need this image for a paper, is to save it as vector graphics (.svg, .eps, ...), as you should for academic papers anyway, and manually edit the image file in your IDE to find and change the title.

**Comment by remz1337** [comment]
Thanks for the tip! That workaround should do the trick while we investigate the issue further.

**Comment by wjdragon** [comment]
I think the issue is [here](https://github.com/alandefreitas/matplotplusplus/blob/95075dc7f960ed920160be510d64638c1260d429/source/matplot/core/axes_type.cpp#L73)

The command to generate the title ('set title') starts with the escaped double quote [here](https://github.com/alandefreitas/matplotplusplus/blob/95075dc7f960ed920160be510d64638c1260d429/source/matplot/core/axes_type.cpp#L59).  The ending escaped double quote is only appended if the support_fonts() section is entered.

I propose the following modification
```
if (parent_->backend_->supports_fonts()) {
    cmd += "\" font \"" + escape(font()) + "," +
        std::to_string(unsigned(font_size() * title_font_size_multiplier_)) + "\"";
    cmd += " textcolor '" + to_string(title_color_) + "'";
}
else {
    cmd += "\"";
}
```
Alternatively, we could force the escaped double quote right before the support_fonts() section.
```
if (title_enhanced_ && iequals(title_font_weight_, "italic")) {
    cmd += "}";
}
cmd += "\"";
if (parent_->backend_->supports_fonts()) {
    ...
```

**Comment by alandefreitas** [comment]
@wjdragon , thanks for finding that.

So

```cpp
if (title_enhanced_ && iequals(title_font_weight_, "italic")) {
    cmd += "}";
}
cmd += "\"";
if (parent_->backend_->supports_fonts()) {
    cmd += " font \"" + escape(font()) + "," +
```

?

Would you like to open this PR?

**Comment by wjdragon** [comment]
Agreed.  Building and testing this fix, will submit if successful

**Comment by pwnorbitals** [comment]
@wjdragon had any success ?

**Comment by wjdragon** [comment]
I tested it and it works fine with the patch.  See PR
https://github.com/wjdragon/matplotplusplus/commit/735dc103c6139fae61a02853eb264484c68843a6

**Comment by alandefreitas** [comment]
By the way, thanks again @wjdragon !

**Comment by ianyepan** [comment]
Ran into the same bug with "enhanced" in plot title and came across this thread. Are there any plans to update the AUR package for Arch-based users as well: https://aur.archlinux.org/packages/matplotplusplus?
