### ISSUE TITLE
Adding Matplot++ to CMakeLists.txt Breaks Project's C++20 Compilation

### ISSUE THREAD

**Issue by xanderdunn** [alandefreitas/matplotplusplus#165]
**Bug category**

- [x] *bug - compilation error*

**Describe the bug**
Adding Matplot++ to my project with `find_package(Matplot++ CONFIG REQUIRED)` break C++20 compiler functionality. 

**Steps to Reproduce**

```bash
wget https://github.com/alandefreitas/matplotplusplus/archive/refs/tags/v1.1.0.zip
unzip v1.1.0.zip
cd matplotplusplus-1.1.0
mkdir build
cd build
cmake ..
make -j 12
make install
```

Add to my project's CMakeLists.txt:
```
set(CMAKE_CXX_STANDARD 20)
find_package(Matplot++ CONFIG REQUIRED)
```

Now attempt to compile some code that makes use of a C++20-only feature, such as calling `contains` on a `std::set`. Compilation fails with:
```
/home/xander/dev/my_model/src/MyClass.cpp: In member function ‘void ccplutus::MyClass::read_batch(const std::shared_ptr<arrow::RecordBatch>&)’:
/home/xander/dev/my_model/src/MyClass.cpp:54:28: error: ‘class std::unordered_set<long int>’ has no member named ‘contains’
   54 |         if (!this->items.contains(market)) {
      |                            ^~~~~~~~
```

This is particularly perplexing  because this is not Matplot++ code that is failing to compile (it's already been compiled), this is my own code that is failing to compile simply because a `find_package` was added to my CMakeLists.txt. Commenting out the `find_package(Matplot++...)` trivially fixes the build.

**Platform**

- [x] *cross-platform issue - linux*

**Environment Details:**
 - OS: Ubuntu
 - OS Version: 18.04
 - Compiler: GCC
 - Compiler version: 10.3.0

**Comment by xanderdunn** [comment]
It looks like I was able to fix this for the time being by adding another `set(CMAKE_CXX_STANDARD 20)` to my CMakeLists.txt this time after the `find_package(Matplot++ CONFIG REQUIRED)`. It appears the Matplot++ .cmake is overriding the global `CXX_STANDARD` when the package is found, requiring me to reset my `CXX_STANDARD`. This does not seem to be desirable?

**Comment by alandefreitas** [comment]
It seems like everyone used to set `set(CMAKE_CXX_STANDARD 17)` manually in the past, like we do [here](https://github.com/alandefreitas/matplotplusplus/blob/abd69a4dfc316bebdca56f093371f75fee6e17be/CMakeLists.txt#L7), but the good practice is to set `target_compile_features(matplot PUBLIC cxx_std_17)` for the target, like we do [here](https://github.com/alandefreitas/matplotplusplus/blob/abd69a4dfc316bebdca56f093371f75fee6e17be/source/matplot/CMakeLists.txt#L112). So you're right. We implemented the good practice but didn't remove the bad practice.

**Comment by xanderdunn** [comment]
Thanks @alandefreitas - I also updated my usage to `target_compile_features` rather than `set(CMAKE_CXX_STANDARD)`

**Comment by MikeGitb** [comment]
I'm comming here, because I also encountered this issue (had an old version installed).


With respect to the merged fix from @leha-bot (https://github.com/alandefreitas/matplotplusplus/pull/181) I'd ask you to not touch CMAKE_CXX_STANDARD at all (when using this library). 
Twhree reasons for this:
- When CMAKE_CXX_STANDARD  ist not set, I expect my project to be compiled with whatever is the compiler's standard version. If my compiler defaults to c++20, the new logic will "downgrade" the standard to 17
- It is extremely suprising (and hard to debug) behavior when a call to find_package(lib) in the middle of my CMake script suddenly switches the c++ standard and half my project gets compiled with say c++14 and the other with c++17 - even if I don't link matplotplusplus to a particular target.
- There are (unfortunately) many different ways to change the c++ standard for a given target in a cmake project (e.g. using raw compiler flags, the `cxx_std_XX` compile feature, setting the CXX_STANDARD property on a target manually and using the `CMAKE_CXX_STANDARD` setting are the ones that come to my mind). Just checking if `CMAKE_CXX_STANDARD` is set isn't enough to determine, if the user has already explicilty decided with which version he/she wants to compile the executable with.

If you really want to make sure that your consumer automatically switches to at least c++17 please use the `target_compile_features(matplot PUBLIC cxx_std_17)` suggested by alandefreitas and leave CMAKE_CXX_STANDARD alone.

An Alternative is to just error out (with a useful error message) if the user tries to use the library without compiling the target in c++17 mode.

**Comment by alandefreitas** [comment]
@MikeGitb , that makes sense. Do you want to open a PR?

**Comment by MikeGitb** [comment]
@alandefreitas : Realistically not anytime soon. I don't have a system,where I can test this filesystem detection logic in a meaningful way. 
Also, considering this file seems to be a copy of (https://github.com/vector-of-bool/CMakeCM/blob/master/modules/FindFilesystem.cmake) I wonder if it wasn't more prudent to try to isolate the effects  and/or change the upstream version instead of modifying the file here. I've no idea, what happens if a project uses two libraries with different versions of that script.

But if I did: What would you prefer:  Attach `cxx_std_17` or just a compilation/config error?

**Comment by alandefreitas** [comment]
> For one, and most importantly, I don't have a system, where I can test this filesystem detection logic in a meaningful way.

Github actions will test the PR on the supported environments. There's also an integration test in there.

>  What would you prefer: Attach cxx_std_17 or just a compilation/config error?

Good question. For any new project, I would just attach cxx_std_17. The filesystem library has been there for a while now. One problem is FindFilesystem also looks for <experimental/filesystem>, but I believe we are at a point where we can just deprecate that since it's a C++17 library anyway.
