### ISSUE TITLE
How to install the library on the global system

### ISSUE THREAD

**Issue by SignificantCell2** [alandefreitas/matplotplusplus#20]
Hello, 
I've downloaded the library, and compiled it. but how to install it on the system? I mean something like:
```
sudo make install
```

Or do I have to compile this library for every project I use?
Please give more details on how to install the dependencies, (even the extra libraries) like GLAD. etc.

Thanks

**Comment by lacc97** [comment]
This is explained in the [Integration](https://github.com/alandefreitas/matplotplusplus#integration) section of the README.

**Comment by SignificantCell2** [comment]
@lacc97 : it is not explained there; this is why I opened this issue.

**Comment by lacc97** [comment]
That section indicates that to use this library you must add it as a subdirectory in your project (whether manually via `add_subdirectory` or with CPM).

Unfortunately, there is currently no way to install the library system wide.

The main dependencies are automatically downloaded by CMake. Gnuplot and the optional dependencies should be obtained through a package manager. On Linux, this is just your distro package manager (e.g. `apt`, `yum` or  whatever). Since I don't use Windows or Mac I can't help you in those cases.

**Comment by SignificantCell2** [comment]
I am using Ubuntu 20.04. I have compiled the library and I tried some examples and it works fine.
The issue is that the installation is not at all clear. it assumes the user to know CMake. What if I don't know cmake, how can I use it with other build system? I could find that in that in the README.md but it is not at all clear:
>If you're not using Cmake, your project needs to include the headers and compile all source files in the source directory. You also need to link with the dependencies described in source/matplot/FindDependencies.cmake.

If I don't know  cmake how am I supposed to know the dependencies in a cmake file.
I hope you make the installation more clear for new users and beginners

Thanks

**Comment by lacc97** [comment]
This library is pretty new; it went public less than 2 days ago and its essentially in alpha. Right now it really doesn't have support for anything other than CMake. If you really wanted to use it in another build system you pretty much have to rewrite the entire build system.

If you're looking for resources to learn CMake, [this book](https://cliutils.gitlab.io/modern-cmake/) is fairly in depth.

**Comment by alandefreitas** [comment]
I would say it offers CMake as the only integration option for now, rather than say it assumes the user knows CMake. I'm sure some other options are going to be available soon. Creating an installer with CMake install is not that complicated. We're just not there yet. 

In any case, I'll update the README.md and make it more clear with something along the lines of what @lacc97 said: "If you really wanted to use it in another build system you pretty much have to rewrite the entire build system."

**Comment by alandefreitas** [comment]
That should solve it for now.
https://github.com/alandefreitas/matplotplusplus/commit/512b82d6a91a69f5d27125d6af4a1b021e264874

In the future, we can put an install command in the build script (https://cmake.org/cmake/help/v3.13/command/install.html) for users who are not on CMake.

**Comment by s1291** [comment]
Thank you very much.

**Comment by alandefreitas** [comment]
That should help you too: https://github.com/alandefreitas/matplotplusplus/pull/25
