### ISSUE TITLE
Default font is not cross platform

### ISSUE THREAD

**Issue by xnorpx** [alandefreitas/matplotplusplus#26]
When plotting with gnuplot on windows, Helvetica is not available by default. Would it be ok to use alternative on Windows?

.\example_plot_1.exe

`(process:23384): Pango-WARNING **: 17:16:06.198: couldn't load font "Helvetica Not-Rotated 200", falling back to "Sans Not-Rotated 200", expect ugly output.`

**Comment by xnorpx** [comment]
I am happy to provide and test patch if you give pointers how you would like it implemented.

**Comment by alandefreitas** [comment]
Yes. The implementation would be very simple. It's just a matter of changing this line: https://github.com/alandefreitas/matplotplusplus/blob/424b8ef2a67ca4c2cfde0d01e64f44c4c490a428/source/matplot/core/figure.h#L300
In the future, the default font should probably come from the backend_interface.

It would be OK to use an alternative as default on windows. The challenge is we would have to:
- Compare fonts to discover which alternatives would look similar or better, and proportional, in the plot categories. 
- Also, to have a look at the examples to make sure the new font doesn't disrupt the examples too much. This isn't expected to happen but it's always good to have a look. You can generate all the examples at once with the target in the `test` directory. That's how we "unit test" the library since tests involve making sure the figures still look good.
- Maybe something like that can serve as a starting point: https://www.creativebloq.com/typography/alternatives-helvetica-7133649 or https://www.lifewire.com/what-fonts-look-like-helvetica-1077403
Otherwise, it would be just as bad as letting it fall back to the default "Sans" option.

Anyway, I don't know if that's documented outside the headers but you can get the figure handle with `auto f = gcf();` and set its font with `f->font("FontName");`.

**Comment by alandefreitas** [comment]
This commit 7e7544c1963b90e793432ec27d3edd3f76fe7077 defines "Sans" as the default font on windows. It's not a perfect solution in the sense that it might not be the most similar font to Heveltica, but it's at least what gnuplot and fontconfig think it's most similar to Helvetica. If there's no heveltica, gnuplot will fallback to this general "Sans" category anyway, so at worst, we are avoiding that annoying and unnecessary warning. It's not a perfect solution because the plots will still look different but it addresses the issue. We can later start a more specific discussion if we want a fancier solution.

**Comment by xnorpx** [comment]
Thanks!
