### ISSUE TITLE
On ubunto Cmake returns: CMake Error at cmake/FindFilesystem.cmake:246 (message):

### ISSUE THREAD

**Issue by paklau99988** [alandefreitas/matplotplusplus#32]
``
-- Looking for IceConnectionNumber in ICE - found
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - not found
CMake Error at cmake/FindFilesystem.cmake:246 (message):
  Cannot run simple program using std::filesystem
Call Stack (most recent call first):
  source/matplot/CMakeLists.txt:1 (find_package)
``

**Comment by paklau99988** [comment]
Fixed with upgrade to gcc 8. Should be documented.

**Comment by nspo** [comment]
The g++ version it's trying to use is too old and does not have the lib in the expected namespace. You can try to delete all build files, install a newer g++ (e.g. g++-8 if you're on Ubuntu 18.04), `export CXX=g++-8` and rerun cmake. On the PC I just tried it on with Ubuntu 18.04 it still did not compile after doing this due to another system library being incompatible with C++17.

**Comment by paklau99988** [comment]
will test g+++8. 
Can no run graphic application inside docker container I think, is very hard.

**Comment by nspo** [comment]
I meant to consider updating the base system to Ubuntu 20.04 if that's possible for you.

I agree that running graphical applications via Docker is not optimal - here are a few options though: http://wiki.ros.org/docker/Tutorials/GUI

**Comment by paklau99988** [comment]
g++8 is solve first problem, thanks you

**Comment by alandefreitas** [comment]
Maybe we could improve the error message but it seems like the build script did what's supposed to do then.
