### ISSUE TITLE
cmake fails when looking for filesystem

### ISSUE THREAD

**Issue by martiege** [alandefreitas/matplotplusplus#49]
**Bug category**

- [x] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ ] *bug - runtime error*
- [ ] *bug - runtime warning*

**Describe the bug**
CMake failes on building as it cannot find std::filesystem. 

**Steps to Reproduce**

```bash
mkdir build
cd build
cmake .. <options> -DCMAKE_BUILD_TYPE=Release
```

**Output**

<details>
 
```console
CMAKE_MODULE_PATH=/home/martin/test/plotting/matplotplusplus/cmake
-- A library with LAPACK API found.
CMake Error at matplotplusplus/cmake/FindFilesystem.cmake:246 (message):
  Cannot run simple program using std::filesystem
Call Stack (most recent call first):
  matplotplusplus/source/matplot/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/martin/test/plotting/CMakeFiles/CMakeOutput.log".
See also "/home/martin/test/plotting/CMakeFiles/CMakeError.log".

```
</details>

**Platform**

- [x] *cross-platform issue - linux*
- [ ] *cross-platform issue - windows*
- [ ] *cross-platform issue - macos*

**Environment Details:**
 - OS: Ubuntu
 - OS Version: 18.04.5
 - Compiler: GCC
 - Compiler version: 7.5.0

**Additional context**

**Comment by lacc97** [comment]
GCC7 is too old and doesn't have full support for `std::filesystem`. You will have to update to GCC8.

**Comment by alandefreitas** [comment]
I tried to improve the documentation a little but there's not much we can do.

**Comment by martiege** [comment]
Ah I see, sorry I thought gcc 7.5.0 could use c++17, and therefore also std::filsystem. Thank you!

**Comment by kurogane1031** [comment]
Sorry for commenting on closed thread. 
For people who using has gcc 7.5.0 built in or olders (For example like Ubuntu 18.04 comes with 7.5.0), you need to first switch your compiler using `update alternatives`. (Do not overwrite your linked it to new compiler)
This is because, for whatever reason, despite using `env CXX=g++-10 cmake ..` during configuration, it will select whatever current g++ version for compilation. To check your current version, just type `g++ --version`. 

To be able to compile, just do as follows

```
sudo apt install build-essential
```
Then install whatever new version, for example if you want to install g++-10, then you need to do as follows
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt install g++-10
```
Then link the g++/gcc to `update alternatives`

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 7
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 7
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
```

Once above is completed, then you can freely change your version as follows
```
update-alternatives --config g++
```
then select which g++ version you would like to use. The same goes to gcc.
```
update-alternatives --config g++
```

Before do cmake, make sure to delete the previous cmake generated files.

After that, you can run `cmake .. <options> -DCMAKE_BUILD_TYPE=Release`.

But in case `std::filesystem` is still not found, (I found in my case, most of the time things will work by deleting previous cmake generated files), then run
`env CC=gcc-10 CXX=g++-10 cmake .. <options> -DCMAKE_BUILD_TYPE=Release`

Hope this helps. It works in my case, so in case it also works for yours, please do tell.

**Comment by alandefreitas** [comment]
Hi @kurogane1031, 

Thanks for making this summary. I'll try to move some of that to the README when I have some time.

**Comment by finnBsch** [comment]
I'm on gcc9 and still have this error. Any Idea?

**Comment by alandefreitas** [comment]
On GCC9 and still `Cannot run simple program using std::filesystem`? Or is it some other error now?
If you're getting `Cannot run simple program using std::filesystem` with GCC9, you're *probably* not using GCC9 or its standard library in your project.

**Comment by finnBsch** [comment]
Yes. How can i find out? I am using clion on windows with mingw. Running gcc --version still says gcc9. When I tried gcc 10 I get a different error (/wd4305 no such file or directory and /uff-8 no such file or directory). Happens only when I try to use marplot++, without it everything compiles fine.

**Comment by alandefreitas** [comment]
I though it was GCC9 on linux. I didn't know it was minnow on windows. That's an important detail.

We don't test continuous integration with mingw+windows. We usually only test macOS+clang, linux+gcc, and windows+msvc. On windows, I would just recommend using visual studio. CLion can directly use visual studio now.

On windows+mingw, the error `Cannot run simple program using std::filesystem` means the standard library doesn't have the filesystem library, which is a C++17 library. The `/wd4305 no such file or directory and /uff-8 no such file or directory` errors mean the build system is trying to apply the necessary MSVC options (because it's windows) but it can't because you're using mingw. The build script would need new flags and conditions to learn to differentiate windows+msvc from windows+mingw.

That's not to say it's impossible to use matplot++ with windows+mingw, but you would need to take care of these details yourself, because there are only so many combinations we can continually test in our workflows.

**Comment by lukac** [comment]
I am getting the exact same error on windows+msvc, using latest MSVS 2022.

**Comment by Neovet** [comment]
Same error here, `Cannot run simple program using std::filesystem`.
Linux, gcc, CMAKE_CXX_COMPILER_VERSION: 12.2.1
Adding lib using `CPMAddPackage("gh:alandefreitas/matplotplusplus@1.1.0")`

**Comment by BrainSlayer** [comment]
same error here. gcc 12.3.0
