### ISSUE TITLE
Why was my issue deleted the last time?

### ISSUE THREAD

**Issue by SignificantCell2** [alandefreitas/matplotplusplus#58]
dear @alandefreitas :
Could you please explain why my last issue was deleted?

Regards

**Comment by alandefreitas** [comment]
Hi @SignificantCell2 ,

Yes, I can. People around here are always willing to dedicate their valuable time to help others however they can. To contribute, answer questions, and solve issues. They could be doing many other fun things with their time rather than being here.

I deleted your issue because I considered the last message to be rude and not constructive. Anyone is always welcome to contribute or ask for help. We just don't want this amazing environment to become twitter or something like that.

I guess these guidelines could apply here: https://news.ycombinator.com/newsguidelines.html But I hope we can just count on common-sense.

Best,

**Comment by SignificantCell2** [comment]
Thank you for your reply
I do greatly appreciate your work and time dedicated to develop this amazing library. Thank you.
I apologize if you find my last post rude. I've never thought it like that I was just asking and maybe because english is not my native language, things went wrong
Thank you very much.
Please feel free to delete this issue too.

**Comment by alandefreitas** [comment]
No worries. I'm sure it wasn't intentional. I also understand how computers can be frustrating when things don't go well. People also have different thresholds for what they consider rude. Feel free to open issues and ask questions.

In any case, I don't want contributors to be demotivated. They spend many hours trying to help others. So I hope you can understand why, in doubt, I'd rather err on the side of politeness. 

I believe this "issue" is solved, so I'm closing it. Best,
