### ISSUE TITLE
Gnuplot window stays in background

### ISSUE THREAD

**Issue by PJ127** [alandefreitas/matplotplusplus#60]
**Bug category**

- [ ] *bug - compilation error*
- [ ] *bug - compilation warning*
- [ ] *bug - runtime error*
- [ ] *bug - runtime warning*
- [x ] *bug - logic error*

**Describe the bug**
I wrote the simplest program with matplot++. It compiles, launches, but the windows stays behind.
The only way to get it in front was complicated (select the window in the taskbar with the mouse, press Alt, press Space, go down the menu and select Maximize). The plot is drawn correctly. Hovering over the taskbar gnuplot icon does not display the plot.

On linux, I do not have this problem. Nor or Windows gnuplot, which displays the plot correctly.

**Steps to Reproduce**

```bash cpp
int main(int argc, char **argv) {
    using namespace matplot;
    std::vector<double> x = linspace(0, 2 * pi);
    std::vector<double> y = transform(x, [](auto x) { return sin(x); });
    plot(x, y, "-o");
    show();
    return 0;
}
```

**Platform**

- [ ] *cross-platform issue - linux*
- [x ] *cross-platform issue - windows*
- [ ] *cross-platform issue - macos*

**Environment Details:**
 - OS: Windows 10
 - OS Version: 
 - Compiler: msys2/mingw
 - Compiler version:

**Additional context**

_NB: the matplot installation did not work perfectly, as I had to manually copy the libmatplot.dll into the installation directory._

Thank you for your help.

**Comment by alandefreitas** [comment]
Hi @PJ127 , Thanks for the feedback.

Do you know which is your default gnuplot terminal? (You can find that out with `gnuplot --term`)

Which installer did you use? To what directory was libmatplot.dll sent initially?

**Comment by xnorpx** [comment]
wxt term works best for me in Windows. QT was slow and Windows one I experience similar issues as described here.

**Comment by PJ127** [comment]
Hello @alandefreitas .
Thank you for your answer.
My gnuplot indicates: "Version 5.2 patchlevel 8    last modified 2019-12-01" (gnuplot --term does not return anything)

I installed the lib with cmake on a msys2 terminal:
```bash
git clone http://github.com/alandefreitas/matplotplusplus
cd matplotplusplus/
mkdir compil-release && cd compil-release 
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX="${REP_BIB}/matplot1.0.1" 
make -j4 && make install
```
I had to manually copy the .lib or the .dll (shared mode):
```bash
cp source\matplot\Release\matplot.dll "${REP_BIB}/matplot1.0.1/lib" 
```

**Comment by alandefreitas** [comment]
@PJ127 
I'm sorry. The command should be `gnuplot -e "show term"`.
It seems like Qt is the default gnuplot terminal on windows but some people are [complaining](https://sourceforge.net/p/gnuplot/mailman/message/35872744/) it's a little problematic.

If it's Qt, maybe you can try what @xnorpx recommended above.
You should be able to change your default terminal with [these instructions](https://stackoverflow.com/questions/19988625/how-to-set-default-terminal-of-gnuplot) or by changing the environment variable `GNUTERM`.

You can also change the terminal directly on matplot++ but I wouldn't recommend that. 
It's more complicated and your code would become be less portable.

Regarding the installer, if you run:

```bash
cmake --install .
```

cmake will try to find your default directory for libraries, but that's not perfect. There are lots of systems where it can't do that for lots of different reasons. I included some more instructions in the documentation this week. 

Did it really install the library in `source\matplot\Release\`? Because that's where the binaries should be *before* installing the library.

@xnorpx 
Is [that](https://sourceforge.net/p/gnuplot/mailman/message/35872744/) also your experience? Do you think it would be reasonable to force matplot++ to use wxt as the default terminal on windows? Or would that be too much?

**Comment by PJ127** [comment]
```
 terminal type is windows 0 color solid butt enhanced standalone
```
Terminal is Windows, and not Qt (GNUTERM=qt with your command line returns `terminal type is unknown`, and same for x11 by the way).

Setting GNUTERM=wxt in my env makes the plot visible and accessible, thank you very much!

No, you are right, the .dll was created in `source\matplot` during the build, but never installed anywhere (`libmatplot.dll.a` was installed correctly though); therefore I had to manually copy the dll. 

_Note_: when using Visual Compilation instead of Unix Makefiles, the problem did not appear, and the .lib was installed correctly.

**Comment by xnorpx** [comment]
@alandefreitas 

Since we now have 2 instances of this happening and wxt seems to work better. I think it's fair to try to force it to wxt on windows with comments why and choice for people to change. (most users of this lib probably just want it to work and pre configure it to do just that would be great I think)

**Comment by alandefreitas** [comment]
OK. I'll do that. It's not that simple because the implemention has to make sure wxt is available and the user hasn't explicitly chosen another default terminal before setting the terminal to wxt, but it's possible.

**Comment by codygray** [comment]
I reproduce on Windows 10 with Gnuplot v5.2.8 with `GNUTERM` set to `windows`. It seems that there is a bug in Gnuplot, where when it is rendering with the `windows` terminal, it moves the plot window off the screen. I suspect this may be a multiple monitor bug; I don't have any single-monitor systems to test on for the purposes of confirming this theory.

Indeed, the problem goes away when setting `GNUTERM` to `wxt`. I have no issue with making `wxt` the default, but things like this create an extraordinarily bad user experience. Worse, they seem to be things outside of the control of Matplotplusplus, which highlights the disadvantage of depending on third-party executables like Gnuplot.

**Comment by alandefreitas** [comment]
That's interesting. If GNUTERM doesn't exists, it should go to wxt on windows:
https://github.com/alandefreitas/matplotplusplus/blob/b45015e2be88e3340b400f82637b603d733d45ce/source/matplot/backend/gnuplot.cpp#L57
